title: Bex's fitness blog
description: > # this means to ignore newlines until "baseurl:"
  My fitness blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Becky # add your name
author-img: rebecca.jpg # add your photo
about-author: A blog documenting my fitness journey.
github: bexfitmeansbexfit # add your Github handle
instagram: bexgainfitstagram # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman