title: bexfitmeansbexfit
description: > # this means to ignore newlines until "baseurl:"
  My fitness blog
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rebecca Felton # add your name
author-img: rebecca-felton.jpg # add your photo
about-author: I am an aspiring solicitor who also loves to keep fit.
github: bexfitmeansbexfit # add your Github handle
instagram: # add your Email address

# Disqus
discus-identifier: dint-care # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
